### ISSUE TITLE
make the mask overlap into the image a little bit

### ISSUE THREAD

**Issue by zeke** [replicate/outpainter#3]
When playing around with outpainting manually, I noticed that I got better results if the mask overlapped the boundaries of the input image a bit, rather then being exactly on the edge. Without this, you sometimes end up with an outpainting that is very separate and incoherent like this one:

<img width="572" alt="Screenshot 2023-06-13 at 1 10 30 PM" src="https://github.com/replicate/outpainter/assets/2289/8e7b0962-4036-410d-8216-e771eaacd8d3">

I realize this may not be totally clear. I can follow up with a graphic to illustrate the point.

**Comment by Pwntus** [comment]
Yes I understand and that makes sense. It's unclear though for me if the black mask square should be "larger" or "smaller" than the initial input image.

I tested it and so far it looks like the black mask square should be "smaller". The black in this context represents what should remain of the initial input image, so by making it "smaller" than the initial input image we're essentially giving up the edges to the Stable Diffusion process - which in turn may give a better "blend".

I "fixed" this here, where you can change it from adding or subtracting the mask overlap: https://github.com/replicate/outpainter/commit/9f873000526c62090e5600a18e2ed0f85caf43b5#diff-1bb47f64a60a39f2bf6f26cf6c92b694351a085663277a1be1262435ac0c6aa4R132

**Comment by zeke** [comment]
> I tested it and so far it looks like the black mask square should be "smaller". The black in this context represents what should remain of the initial input image, so by making it "smaller" than the initial input image we're essentially giving up the edges to the Stable Diffusion process - which in turn may give a better "blend".

Exactly!
